CREATE TABLE `caseProfileAttachments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`caseProfileId` int NOT NULL,
	`filename` varchar(255) NOT NULL,
	`originalName` varchar(255) NOT NULL,
	`fileSize` int NOT NULL,
	`mimeType` varchar(100) NOT NULL,
	`fileType` enum('DOCUMENT','IMAGE','VIDEO','AUDIO') NOT NULL,
	`s3Key` varchar(500) NOT NULL,
	`s3Url` text NOT NULL,
	`displayOrder` int NOT NULL DEFAULT 0,
	`caption` text,
	`virusScanned` boolean NOT NULL DEFAULT false,
	`scanResult` varchar(50),
	`uploadedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `caseProfileAttachments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `caseProfileUpdates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`caseProfileId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`content` text NOT NULL,
	`updateReason` text,
	`status` enum('DRAFT','PENDING_APPROVAL','APPROVED','PUBLISHED','REJECTED') NOT NULL DEFAULT 'DRAFT',
	`isPublished` boolean NOT NULL DEFAULT false,
	`publishedAt` timestamp,
	`submittedByUserId` int,
	`approvedByUserId` int,
	`approvalNotes` text,
	`approvedAt` timestamp,
	`generatedSeoContent` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `caseProfileUpdates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `caseProfiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`submissionId` int,
	`profileSlug` varchar(200) NOT NULL,
	`title` varchar(255) NOT NULL,
	`summary` text NOT NULL,
	`category` enum('CIVIL_RIGHTS','POLICE_MISCONDUCT','LEGAL_MALPRACTICE','PROSECUTORIAL_MISCONDUCT','CONSTITUTIONAL_VIOLATION','INSTITUTIONAL_CORRUPTION','OTHER') NOT NULL,
	`jurisdiction` enum('Montana','Washington','Federal','Multi-State') NOT NULL,
	`allegedOrganizations` text,
	`fullContent` text,
	`metaTitle` varchar(200),
	`metaDescription` text,
	`seoKeywords` text,
	`generatedSeoContent` text,
	`status` enum('DRAFT','PENDING_APPROVAL','APPROVED','PUBLISHED','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
	`isPublished` boolean NOT NULL DEFAULT false,
	`publishedAt` timestamp,
	`submittedByUserId` int,
	`approvedByUserId` int,
	`approvalNotes` text,
	`approvedAt` timestamp,
	`viewCount` int NOT NULL DEFAULT 0,
	`shareCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `caseProfiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `caseProfiles_profileSlug_unique` UNIQUE(`profileSlug`)
);
