CREATE TABLE `notificationPreferences` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`emailNotificationsEnabled` boolean NOT NULL DEFAULT true,
	`emailOnCaseUpdate` boolean NOT NULL DEFAULT true,
	`emailOnMessage` boolean NOT NULL DEFAULT true,
	`emailOnProfilePublished` boolean NOT NULL DEFAULT true,
	`emailDigestFrequency` enum('IMMEDIATE','DAILY','WEEKLY','NEVER') NOT NULL DEFAULT 'IMMEDIATE',
	`inAppNotificationsEnabled` boolean NOT NULL DEFAULT true,
	`showNotificationBadge` boolean NOT NULL DEFAULT true,
	`pushNotificationsEnabled` boolean NOT NULL DEFAULT false,
	`receiveSystemUpdates` boolean NOT NULL DEFAULT true,
	`receiveAdminAlerts` boolean NOT NULL DEFAULT true,
	`receiveMarketingEmails` boolean NOT NULL DEFAULT false,
	`doNotDisturbEnabled` boolean NOT NULL DEFAULT false,
	`doNotDisturbStart` varchar(5),
	`doNotDisturbEnd` varchar(5),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `notificationPreferences_id` PRIMARY KEY(`id`),
	CONSTRAINT `notificationPreferences_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `notifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`type` enum('CASE_SUBMITTED','CASE_APPROVED','CASE_REJECTED','CASE_UPDATE','MESSAGE_RECEIVED','ADMIN_ALERT','SYSTEM_UPDATE','RESOURCE_ADDED','PROFILE_PUBLISHED','PROFILE_UPDATE_APPROVED','PROFILE_UPDATE_REJECTED','CUSTOM') NOT NULL,
	`title` varchar(255) NOT NULL,
	`message` text NOT NULL,
	`relatedCaseId` int,
	`relatedSubmissionId` int,
	`relatedCaseProfileId` int,
	`relatedMessageId` int,
	`priority` enum('LOW','NORMAL','HIGH','URGENT') NOT NULL DEFAULT 'NORMAL',
	`icon` varchar(50),
	`actionUrl` text,
	`actionLabel` varchar(100),
	`isRead` boolean NOT NULL DEFAULT false,
	`readAt` timestamp,
	`sentViaEmail` boolean NOT NULL DEFAULT false,
	`emailSentAt` timestamp,
	`sentViaPush` boolean NOT NULL DEFAULT false,
	`pushSentAt` timestamp,
	`expiresAt` timestamp,
	`isArchived` boolean NOT NULL DEFAULT false,
	`archivedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `notifications_id` PRIMARY KEY(`id`)
);
